# Generated by Django 4.2.5 on 2023-10-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('gols', models.IntegerField(default=0, verbose_name='Gols')),
                ('assistencias', models.IntegerField(default=0, verbose_name='Assistências')),
                ('vitorias', models.IntegerField(default=0, verbose_name='Vitórias')),
                ('amarelos', models.IntegerField(default=0, verbose_name='Amarelos')),
                ('vermelhos', models.IntegerField(default=0, verbose_name='Vermelhos')),
                ('deivid', models.IntegerField(default=0, verbose_name='Deivid')),
                ('puskas', models.IntegerField(default=0, verbose_name='Puskas')),
                ('bolaCheia', models.IntegerField(default=0, verbose_name='Bola Cheia')),
                ('bolaMurcha', models.IntegerField(default=0, verbose_name='Bola Murcha')),
            ],
        ),
    ]
