# Generated by Django 4.2.5 on 2023-10-31 19:22

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='images', variations={'png': (500, 500)}, verbose_name='Imagem')),
            ],
        ),
    ]
