# Generated by Django 4.2.5 on 2023-10-31 19:35

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_ultimapartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimapartida',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='tcc/images', variations={'png': (500, 500)}, verbose_name='Imagem'),
        ),
    ]
